/* Taurus Magnum CRM — central de alertas de produtividade */
(function(){
'use strict';
var lastSummary={vendas_sem_data:0,acoes_hoje:0,acoes_vencidas:0};
var refreshTimer=null;
function cfg(){return window.CRM_SUPABASE&&window.CRM_SUPABASE.config;}
function token(){var c=cfg();if(!c)return null;try{var s=JSON.parse(localStorage.getItem('sb-'+c.projectRef+'-auth-token')||'null');return s&&(s.access_token||(s.currentSession&&s.currentSession.access_token));}catch(e){return null;}}
function headers(){var c=cfg(),t=token();if(!c||!t)return null;return {'apikey':c.publishableKey,'Authorization':'Bearer '+t,'Content-Type':'application/json','Accept-Profile':c.schema||'crm','Content-Profile':c.schema||'crm'};}
function rpcSummary(){var c=cfg(),h=headers();if(!c||!h)return Promise.resolve(lastSummary);return fetch(c.url+'/rest/v1/rpc/notification_summary',{method:'POST',headers:h,body:'{}'}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(function(rows){var x=Array.isArray(rows)?rows[0]:rows;if(x)lastSummary={vendas_sem_data:Number(x.vendas_sem_data||0),acoes_hoje:Number(x.acoes_hoje||0),acoes_vencidas:Number(x.acoes_vencidas||0)};return lastSummary;}).catch(function(){return lastSummary;});}
function total(s){return Number(s.vendas_sem_data||0)+Number(s.acoes_hoje||0)+Number(s.acoes_vencidas||0);}
function ensureCss(){if(document.getElementById('tm-alert-style'))return;var st=document.createElement('style');st.id='tm-alert-style';st.textContent='#tm-alert-bell{position:relative;width:35px;height:35px;padding:0;display:inline-flex;align-items:center;justify-content:center;border-radius:8px;flex:none}#tm-alert-bell i{font-size:17px}.tm-alert-badge{position:absolute;right:-4px;top:-5px;min-width:17px;height:17px;padding:0 4px;border-radius:999px;background:#ef4444;color:#fff;font-size:9px;font-weight:800;display:flex;align-items:center;justify-content:center;border:2px solid #0e1628}.tm-alert-panel{position:fixed;z-index:7000;width:340px;max-width:calc(100vw - 24px);background:#0e1628;border:1px solid rgba(59,130,246,.28);border-radius:14px;box-shadow:0 18px 55px rgba(0,0,0,.5);overflow:hidden}.tm-alert-head{display:flex;align-items:center;justify-content:space-between;padding:13px 14px;border-bottom:1px solid rgba(59,130,246,.13)}.tm-alert-head strong{font-size:13px}.tm-alert-list{padding:8px}.tm-alert-item{display:flex;gap:10px;padding:10px;border-radius:10px;margin-bottom:5px;background:#111d31;border:1px solid rgba(59,130,246,.10);cursor:pointer}.tm-alert-item:hover{background:#17243b}.tm-alert-dot{width:8px;height:8px;border-radius:50%;margin-top:5px;flex:none}.tm-alert-copy{min-width:0}.tm-alert-copy b{display:block;font-size:12px;color:#e2e8f0;margin-bottom:2px}.tm-alert-copy span{font-size:11px;color:#7c8fa9;line-height:1.35}.tm-alert-empty{padding:22px;text-align:center;color:#64748b;font-size:12px}.tm-alert-red .tm-alert-dot{background:#ef4444}.tm-alert-amber .tm-alert-dot{background:#f59e0b}.tm-alert-orange .tm-alert-dot{background:#fb923c}';document.head.appendChild(st);}
function navTo(page){try{var btn=document.querySelector('.nav-tab[data-tab="'+page+'"]');if(btn&&typeof window.showPage==='function')window.showPage(page,btn);}catch(e){}closePanel();}
function itemHtml(cls,title,desc,page,count){if(!count)return'';return '<div class="tm-alert-item '+cls+'" data-page="'+page+'"><span class="tm-alert-dot"></span><div class="tm-alert-copy"><b>'+title+'</b><span>'+desc+'</span></div></div>';}
function renderPanel(){var p=document.getElementById('tm-alert-panel');if(!p)return;var s=lastSummary,html='';html+=itemHtml('tm-alert-red',s.vendas_sem_data+' venda'+(s.vendas_sem_data===1?'':'s')+' sem data da venda','Preencha a data no cadastro para contabilizar a Receita.','leads',s.vendas_sem_data);html+=itemHtml('tm-alert-amber',s.acoes_hoje+' ação'+(s.acoes_hoje===1?'':'ões')+' para hoje','Há follow-ups programados para hoje.','follow-up',s.acoes_hoje);html+=itemHtml('tm-alert-orange',s.acoes_vencidas+' ação'+(s.acoes_vencidas===1?' vencida':'ões vencidas'),'Existem contatos programados com data já ultrapassada.','follow-up',s.acoes_vencidas);p.querySelector('.tm-alert-list').innerHTML=html||'<div class="tm-alert-empty">Nenhum alerta pendente.</div>';p.querySelectorAll('.tm-alert-item').forEach(function(el){el.onclick=function(){navTo(el.dataset.page);};});}
function updateBadge(){var b=document.querySelector('#tm-alert-bell .tm-alert-badge'),n=total(lastSummary);if(!b)return;if(n>0){b.style.display='flex';b.textContent=n>99?'99+':String(n);}else b.style.display='none';}
function positionPanel(){var btn=document.getElementById('tm-alert-bell'),p=document.getElementById('tm-alert-panel');if(!btn||!p)return;var r=btn.getBoundingClientRect();p.style.top=Math.round(r.bottom+8)+'px';p.style.right=Math.max(12,Math.round(window.innerWidth-r.right))+'px';}
function openPanel(){var p=document.getElementById('tm-alert-panel');if(!p)return;rpcSummary().then(function(){renderPanel();updateBadge();positionPanel();p.style.display='block';});}
function closePanel(){var p=document.getElementById('tm-alert-panel');if(p)p.style.display='none';}
function togglePanel(){var p=document.getElementById('tm-alert-panel');if(!p)return;if(p.style.display==='block')closePanel();else openPanel();}
function ensureUi(){if(document.getElementById('tm-alert-bell'))return true;var nav=document.querySelector('.nav');if(!nav)return false;ensureCss();var btn=document.createElement('button');btn.id='tm-alert-bell';btn.className='nav-btn';btn.title='Alertas de produtividade';btn.setAttribute('aria-label','Alertas de produtividade');btn.innerHTML='<i class="ti ti-bell"></i><span class="tm-alert-badge" style="display:none"></span>';btn.onclick=function(e){e.stopPropagation();togglePanel();};var anchor=document.getElementById('cfg-abas');if(anchor&&anchor.parentNode)anchor.parentNode.insertBefore(btn,anchor);else nav.appendChild(btn);var p=document.createElement('div');p.id='tm-alert-panel';p.className='tm-alert-panel';p.style.display='none';p.innerHTML='<div class="tm-alert-head"><strong>Alertas de produtividade</strong><button class="icon-btn" id="tm-alert-close" aria-label="Fechar"><i class="ti ti-x"></i></button></div><div class="tm-alert-list"></div>';document.body.appendChild(p);document.getElementById('tm-alert-close').onclick=closePanel;document.addEventListener('click',function(e){if(!p.contains(e.target)&&e.target!==btn&&!btn.contains(e.target))closePanel();});window.addEventListener('resize',positionPanel);return true;}
function stretchSaleToast(){var el=document.getElementById('tm-sale-date-alert');if(!el||el.dataset.tmExtended)return;var clone=el.cloneNode(true);clone.dataset.tmExtended='1';el.replaceWith(clone);var b=clone.querySelector('button');if(b)b.onclick=function(){clone.remove();};setTimeout(function(){if(clone&&clone.parentNode)clone.remove();},30000);}
function refresh(){if(!ensureUi())return;rpcSummary().then(function(){updateBadge();var p=document.getElementById('tm-alert-panel');if(p&&p.style.display==='block')renderPanel();});setTimeout(stretchSaleToast,400);}
function boot(){var tries=0,t=setInterval(function(){tries++;if(ensureUi()){clearInterval(t);refresh();}if(tries>80)clearInterval(t);},100);var obs=new MutationObserver(function(){stretchSaleToast();});obs.observe(document.body,{childList:true,subtree:true});window.addEventListener('focus',refresh);window.addEventListener('message',function(ev){if(ev.source===window&&ev.data&&ev.data.type==='CRM_UPDATED'){clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,700);}});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
